/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Colonial_Classic: THREE.Mesh
  }
  materials: {
    concrete_red: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/col_classic_red.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Colonial_Classic.geometry} material={materials.concrete_red} position={[-0.03, 0, -0.46]} />
    </group>
  )
}

useGLTF.preload('/col_classic_red.gltf')
